name: StefanMaven
version: 0.0.8
author: Stefan Cooper
main: com.stefancooper.StefanMaven.Main
api-version: 1.14
website: https://stefancooper.com
commands:
  Magnet:
    description: Items magnet immediately to your inventory on block break. ( This command gives you a Stone Pickaxe to try it out )
    permission: yes
    permission-message: You must be OP!
  AutoSmelt:
    description: If the block broken can be smelted into something else, then it drops that smelted version. IE. Iron Ore -> Iron Ingot. ( This command gives you a Stone Pickaxe to try it out )
    permission: yes
    permission-message: You must be OP!
  ExplosiveBow:
    description: If you hit a target with an arrow, the arrow will explode! ( This command gives you a Bow to try it out )
    permission: yes
    permission-message: You must be OP!
  SwiftPlanter:
    description: Replant harvested crops automatically ( This command gives you a Stone Hoe to try it out )
    permission: yes
    permission-message: You must be OP!
  HunterCompass:
    description: Compass pointing at player
    usage: /hunterCompass [targetPlayer]
  BigBrainMining:
    description: Get more XP from mining ores ( This command gives you a Stone Pickaxe to try it out )
    permission: yes
    permission-message: You must be OP!

#    Future Work:
#       - Lucky Farmer: (Hoes) Fortune for farming (levelled 1-3)
#       - Night Light: (Helmets) Night vision all the time (not levelled)
#       - Hot Hands: (Armour) Small chance of setting attacking enemy on fire (levelled 1-3)
#       - Bad Omen: (Swords) Chance to give wither to enemy (levelled 1-5)








