name: StefanMaven
version: 0.0.4
author: Stefan Cooper
main: com.stefancooper.StefanMaven.Main
api-version: 1.14
website: https://stefancooper.com
commands:
  Magnet:
    description: Gives Stone pickaxe with Magnet enchantment
    permission: yes
    permission-message: You must be OP!
  AutoSmelt:
    description: Gives Stone pickaxe with AutoSmelt enchantment
    permission: yes
    permission-message: You must be OP!
